Create table ODS."BANK"(
    bnk_org_id bigint NOT NULL,
    bnk_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bnk_full_nm varchar(50),
    rtng_num varchar(35) NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bnk_org_id,bnk_id)
)
PARTITION BY COLUMN (bnk_org_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BENEFIT_PACKAGE"(
    bene_pkg_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bene_pkg_cd varchar(20) NOT NULL,
    bene_pkg_typ_ref_id bigint NOT NULL,
    org_id bigint,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bene_pkg_id)
)
PARTITION BY COLUMN (bene_pkg_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_ENTITY"(
    bill_ent_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bill_ent_ref_id bigint NOT NULL,
    grp_id bigint,
    prsn_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id)
)
PARTITION BY COLUMN (bill_ent_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CODE_VALUE"(
    cd_val_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cd_val varchar(50) NOT NULL,
    cd_typ_ref_id bigint NOT NULL,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    PRIMARY KEY (client_id,cd_val_id)
)
PARTITION BY COLUMN (cd_val_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CONTACT"(
    cntc_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cntc_typ_ref_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cntc_id)
)
PARTITION BY COLUMN (cntc_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."GROUPS"(
    grp_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    grp_cd varchar(20),
    grp_typ_ref_id bigint NOT NULL,
    org_id bigint,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id)
)
PARTITION BY COLUMN (grp_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."INQUIRY"(
    inq_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    caller_typ_ref_id bigint NOT NULL,
    is_in_bound SMALLINT,
    track_num varchar(15),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id)
)
PARTITION BY COLUMN (inq_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ORGANIZATIONS"(
    org_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    org_nm varchar(80),
    org_typ_ref_id bigint NOT NULL,
    descr LONG VARCHAR,
    empr_tax_id varchar(25),
    web_site varchar(100),
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,org_id)
)
PARTITION BY COLUMN (org_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_EVENT"(
    prsn_evnt_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    src_typ_id bigint NOT NULL,
    prsn_id bigint,
    attach_src_id bigint,
    evnt_typ_ref_id bigint NOT NULL,
    client_evnt_typ_ref_id bigint,
    evnt_descr LONG VARCHAR,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR NOT NULL,
    PRIMARY KEY (client_id,prsn_evnt_id)
)
PARTITION BY COLUMN (prsn_evnt_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSONS"(
    prsn_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    ttl LONG VARCHAR,
    first_nm LONG VARCHAR,
    last_nm LONG VARCHAR,
    mid_nm LONG VARCHAR,
    sfx LONG VARCHAR,
    birth_dt DATE,
    gndr_ref_id bigint,
    ethn_ref_id bigint,
    mar_stat_ref_id bigint,
    lang_ref_id bigint,
    prsn_stat_ref_id bigint,
    eff_dt DATE,
    expr_dt DATE,
    attach_src_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR NOT NULL,
    PRIMARY KEY (client_id,prsn_id)
)
PARTITION BY COLUMN (prsn_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_REVIEW"(
    um_rvw_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    um_rvw_cd LONG VARCHAR,
    prsn_id bigint,
    bene_grp_id bigint,
    sec_bene_grp_id bigint,
    sec_bene_grp_id_1 bigint,
    crt_mthd LONG VARCHAR,
    usr_id LONG VARCHAR,
    crt_dt DATE,
    pri_diag_cd_id bigint,
    pri_rvwer LONG VARCHAR,
    sec_rvwer LONG VARCHAR,
    acdt_ind LONG VARCHAR,
    acdt_dt DATE,
    acdt_st LONG VARCHAR,
    oth_bene_ind LONG VARCHAR,
    risk_ind_ref_id bigint,
    qlty_ind_ref_id bigint,
    mbr_compl_ref_id bigint,
    serv_to_dt DATE,
    death_dt DATE,
    um_rvw_lnk_id bigint,
    um_lnk_rsn_ref_id bigint,
    inq_id bigint,
    inpt_ind LONG VARCHAR,
    edi_278_rspns_dt DATE,
    rvw_prvd_id bigint,
    alt_um_rvw_id LONG VARCHAR,
    icd_ver_proc LONG VARCHAR,
    icd_ver_inp LONG VARCHAR,
    icd_trnsltn_trn_id LONG VARCHAR,
    sbmt_diag_cd_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id)
)
PARTITION BY COLUMN (um_rvw_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_PAYMENT"(
    clm_pay_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    clm_pay_dt DATE,
    clm_pay_ref LONG VARCHAR,
    clm_pay_typ LONG VARCHAR,
    clm_pay_sub_typ LONG VARCHAR,
    ln_of_bus bigint,
    payee_typ LONG VARCHAR,
    subs_id bigint,
    prvd_id bigint,
    cmb_clm_flg LONG VARCHAR,
    prd_end_dt DATE,
    orig_amt NUMERIC(18,4),
    deductable_amt NUMERIC(18,4),
    clm_pay_net_amt NUMERIC(18,4),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,clm_pay_id)
)
PARTITION BY COLUMN (clm_pay_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_PAYMENT_REDUCTION"(
    clm_pay_rdctn_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pay_rdctn_ref LONG VARCHAR,
    pay_rdctn_sub_typ LONG VARCHAR,
    plan_yr DATE,
    tax_yr DATE,
    pay_rdctn_typ LONG VARCHAR,
    crt_dt DATE,
    payee_typ LONG VARCHAR,
    prvd_id bigint,
    subs_id bigint,
    auto_pay_rdctn_flg LONG VARCHAR,
    rdctn_orig_amt NUMERIC(18,4),
    recovered_amt NUMERIC(18,4),
    recv_amt NUMERIC(18,4),
    wo_amt NUMERIC(18,4),
    rdctn_net_amt NUMERIC(18,4),
    rdctn_stat LONG VARCHAR,
    disallow_explain_cd LONG VARCHAR,
    usr_id LONG VARCHAR,
    prem_typ_flg LONG VARCHAR,
    ext_pay_flg LONG VARCHAR,
    rdctn_descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,clm_pay_rdctn_id)
)
PARTITION BY COLUMN (clm_pay_rdctn_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ADJUSTMENT"(
    bill_ent_id bigint NOT NULL,
    adj_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    adj_typ_ref_id bigint NOT NULL,
    is_cr_adj SMALLINT,
    bill_ent_schd_id bigint NOT NULL,
    adj_amt NUMERIC(18,4) NOT NULL,
    descr LONG VARCHAR,
    post_dt DATE,
    orig_rcpt_id bigint,
    nsf_rsn_ref_id bigint,
    whld_typ_ref_id bigint,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,adj_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BENEFIT_GROUP_NAME"(
    grp_id bigint NOT NULL,
    bene_grp_id bigint NOT NULL,
    bene_grp_nm_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bene_grp_nm varchar(80),
    descr LONG VARCHAR,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,bene_grp_id,bene_grp_nm_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BENEFIT_GROUPS"(
    grp_id bigint NOT NULL,
    bene_pkg_id bigint NOT NULL,
    bene_grp_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bene_grp_cd varchar(50),
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,bene_pkg_id,bene_grp_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_RECONCILIATION"(
    bill_ent_id bigint NOT NULL,
    bill_recon_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cr_typ_ref_id bigint NOT NULL,
    cr_src_id bigint NOT NULL,
    dr_typ_ref_id bigint NOT NULL,
    dr_src_id bigint NOT NULL,
    amt NUMERIC(19,4),
    cncl_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,bill_recon_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_SCHEDULE"(
    bill_schd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    acct_prd_strt DATE,
    acct_prd_end DATE,
    prd_mo_cnt INTEGER,
    bill_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_schd_id)
)
PARTITION BY COLUMN (bill_schd_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_SOURCE"(
    bill_ent_id bigint NOT NULL,
    src_typ_ref_id bigint NOT NULL,
    bill_src_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    client_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,src_typ_ref_id,bill_src_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CHARGE_ITEM"(
    bill_ent_id bigint NOT NULL,
    prem_part_id bigint NOT NULL,
    bill_ent_schd_id bigint NOT NULL,
    chrg_itm_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    chrg_ityp_ref_id bigint NOT NULL,
    chrg_itm_amt NUMERIC(19,4),
    post_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,prem_part_id,bill_ent_schd_id,chrg_itm_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CHECK"(
    clm_pay_id bigint NOT NULL,
    chk_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    chk_seq_num INTEGER,
    chk_num LONG VARCHAR,
    payee_id bigint,
    cashed_dt DATE,
    reissued_dt DATE,
    prnt_dt LONG VARCHAR,
    chk_typ LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,clm_pay_id,chk_id)
)
PARTITION BY COLUMN (clm_pay_id)
COLOCATE WITH (ODS.CLAIM_PAYMENT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM"(
    prsn_id bigint NOT NULL,
    clm_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    subs_id bigint,
    servicing_prvd_id bigint NOT NULL,
    bene_grp_id bigint,
    clm_typ_ref_id bigint NOT NULL,
    clm_sub_typ_ref_id bigint NOT NULL,
    clm_rcv_dt DATE,
    clm_inp_dt DATE,
    last_act_ts TIMESTAMP,
    clm_pd_dt DATE,
    nxt_rvw_dt DATE,
    serv_frm_dt DATE,
    serv_to_dt DATE,
    payee_prvd_id bigint,
    clm_rls_ind LONG VARCHAR,
    cur_illness_dt DATE,
    simillar_illness_dt DATE,
    pcp_id bigint,
    refng_prvd_id bigint,
    pre_auth_num LONG VARCHAR,
    pay_calc_dt DATE,
    clm_ai_eob_ind LONG VARCHAR,
    explain_cd_id bigint,
    img_addr LONG VARCHAR,
    unable_to_wrk_frm DATE,
    unable_to_wrk_to DATE,
    hosp_frm DATE,
    hosp_to DATE,
    lab_svind LONG VARCHAR,
    mdcr_re_subm_num LONG VARCHAR,
    out_of_area_ind LONG VARCHAR,
    xray_ind LONG VARCHAR,
    clm_records_ind LONG VARCHAR,
    clm_proc_dt DATE,
    crtd_frm_clm_id bigint,
    adj_to_clm_id bigint,
    adj_frm_clm_id bigint,
    ntwk_prvd_ent_prfx LONG VARCHAR,
    ntwk_prvd_prfx LONG VARCHAR,
    ntwk_prvd_cap_prfx LONG VARCHAR,
    non_partic_prvd_prfx LONG VARCHAR,
    serv_def_prfx LONG VARCHAR,
    prvd_accum_prfx LONG VARCHAR,
    prcs_ctrl_agnt_prfx LONG VARCHAR,
    mod_prc_rules_prfx LONG VARCHAR,
    prvd_ntwk_id LONG VARCHAR,
    prvd_agree_id LONG VARCHAR,
    mdcr_assign_ind LONG VARCHAR,
    pay_prvd_ind LONG VARCHAR,
    oth_bene_ind LONG VARCHAR,
    acdt_ind LONG VARCHAR,
    acdt_st LONG VARCHAR,
    acdt_dt DATE,
    acdt_amt NUMERIC(40,10),
    ptnt_acct_num LONG VARCHAR,
    ptnt_pd_amt NUMERIC(40,10),
    clm_tot_chrg NUMERIC(40,10),
    clm_tot_pay NUMERIC(40,10),
    chk_cycle_ovrd_ind LONG VARCHAR,
    clm_inp_method LONG VARCHAR,
    clm_aud_ind LONG VARCHAR,
    ext_ref_ind LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLIENT_REFERENCE_DATA"(
    client_ref_dta_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cmn_ref_dta_id bigint,
    ref_ent LONG VARCHAR,
    ref_dmn LONG VARCHAR,
    ref_cd LONG VARCHAR,
    ref_descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,client_ref_dta_id)
)
PARTITION BY COLUMN (client_ref_dta_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLIENTS"(
    client_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    full_client_sys_cd LONG VARCHAR,
    client_sys_cd LONG VARCHAR,
    client_lgcy_cd varchar(3) NOT NULL,
    client_acronym LONG VARCHAR,
    impl_strt_dt DATE,
    go_lve_dt DATE,
    env_cd LONG VARCHAR,
    main_app_cd LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id)
)
PARTITION BY COLUMN (client_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."COB_CLAIM_DIAGNOSIS"(
    prsn_id bigint NOT NULL,
    prsn_cob_id bigint NOT NULL,
    rec_ord INTEGER NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    diag_ind char(1),
    clm_diag_cd varchar(10),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_cob_id,rec_ord)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."COB_ORGANIZATION_PERSON"(
    prsn_id bigint NOT NULL,
    prsn_cob_id bigint NOT NULL,
    org_prsn_typ_ref_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    org_nm varchar(80),
    first_nm varchar(50),
    mid_nm varchar(50),
    last_nm varchar(50),
    empr_tax_id varchar(25),
    ssn varchar(12),
    str_ln1 varchar(100),
    str_ln2 varchar(100),
    cty varchar(75),
    st varchar(50),
    pstl_cd varchar(20),
    phn_num varchar(50),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_cob_id,org_prsn_typ_ref_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."COMMUNICATION"(
    inq_id bigint NOT NULL,
    cmcn_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    track_num varchar(15),
    cntc_id bigint,
    first_nm varchar(50),
    last_nm varchar(50),
    phn_num varchar(50),
    strt_tm TIMESTAMP,
    end_tm TIMESTAMP,
    prsn_id bigint,
    insrt_usr varchar(50),
    upd_usr varchar(50),
    insrt_serv_rec_ts TIMESTAMP,
    upd_serv_rec_ts TIMESTAMP,
    prsn_evnt_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id,cmcn_id)
)
PARTITION BY COLUMN (inq_id)
COLOCATE WITH (ODS.INQUIRY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."COMPLAINT"(
    inq_id bigint NOT NULL,
    complaint_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    complaint_sub_typ_ref_id bigint NOT NULL,
    complaint_typ_ref_id bigint NOT NULL,
    prsn_id bigint,
    aor_prsn_id bigint,
    track_num varchar(15),
    case_id varchar(20),
    expd SMALLINT,
    expd_descr LONG VARCHAR,
    filling_typ_ref_id bigint,
    complaint_descr LONG VARCHAR,
    rts_offr SMALLINT,
    rts_provided SMALLINT,
    info_provided_to_caller LONG VARCHAR,
    rcpt_method_ref_id bigint,
    case_crtd TIMESTAMP,
    due_dt DATE,
    ext_dt DATE,
    ext_rsn LONG VARCHAR,
    close_dt DATE,
    drug_dosage varchar(100),
    drug_nm varchar(100),
    drug_qty varchar(100),
    prescribing_physn_nm varchar(100),
    prescribing_physn_phn varchar(50),
    prescribing_physn_fax varchar(50),
    rslvd_on_call SMALLINT,
    img_recv_dt DATE,
    coor_usr varchar(50),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id,complaint_id)
)
PARTITION BY COLUMN (inq_id)
COLOCATE WITH (ODS.INQUIRY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."DIAGNOSIS_CODE"(
    diag_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    diag_cd LONG VARCHAR,
    diag_descr LONG VARCHAR,
    rltd_diag_cd LONG VARCHAR,
    std_ref_cd_1 LONG VARCHAR,
    std_ref_cd_2 LONG VARCHAR,
    diag_typ LONG VARCHAR,
    expr_dt DATE,
    eff_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,diag_cd_id)
)
PARTITION BY COLUMN (diag_cd_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ELECTRONIC_ADDRESS"(
    cntc_id bigint NOT NULL,
    elec_addr_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    elec_addr varchar(100),
    addr_fmt varchar(50),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cntc_id,elec_addr_id)
)
PARTITION BY COLUMN (cntc_id)
COLOCATE WITH (ODS.CONTACT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ENTITY_BANK_ACCOUNT"(
    bill_ent_id bigint NOT NULL,
    bnk_acct_id bigint NOT NULL,
    ent_bnk_acct_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,bnk_acct_id,ent_bnk_acct_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ETL_METADATA"(
    main_tbl LONG VARCHAR NOT NULL,
    tgt_tbl LONG VARCHAR NOT NULL,
    stmt_id INTEGER NOT NULL,
    col_ord_num INTEGER NOT NULL,
    src_col LONG VARCHAR NOT NULL,
    trnsfrmtn_typ LONG VARCHAR NOT NULL,
    src_tbl LONG VARCHAR NOT NULL,
    tgt_col LONG VARCHAR,
    ref_val_1 LONG VARCHAR,
    ref_val_2 LONG VARCHAR,
    src_ref_typ LONG VARCHAR NOT NULL,
    null_empty_fltr LONG VARCHAR,
    src_key_typ LONG VARCHAR,
    col_fltr LONG VARCHAR,
    PRIMARY KEY (main_tbl,tgt_tbl,stmt_id,col_ord_num)
)
PARTITION BY COLUMN (stmt_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."EXHIBIT"(
    exhibit_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    exhibit_cd_ref_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,exhibit_id)
)
PARTITION BY COLUMN (exhibit_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."EXPLANATION_CODE"(
    explain_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    explain_typ LONG VARCHAR,
    explain_stat LONG VARCHAR,
    sd LONG VARCHAR,
    ld_1 LONG VARCHAR,
    ld_2 LONG VARCHAR,
    explain_lblty_ind LONG VARCHAR,
    edi_clm_stat_cat LONG VARCHAR,
    edi_clm_stat LONG VARCHAR,
    edi_clm_adj_rsn LONG VARCHAR,
    rem_rmrk LONG VARCHAR,
    prvd_adj_rsn LONG VARCHAR,
    hc_plcy_id LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,explain_cd_id)
)
PARTITION BY COLUMN (explain_cd_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."FILE_TRANSFER_RUN"(
    fl_trans_run_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    log_stmp LONG VARCHAR,
    tsk_id bigint,
    node INTEGER,
    nmnl_strt LONG VARCHAR,
    tsk_nm LONG VARCHAR,
    run_rec_typ LONG VARCHAR,
    strt_tm LONG VARCHAR,
    end_tm LONG VARCHAR,
    started_by LONG VARCHAR,
    scss_flg LONG VARCHAR,
    fl_snt_cnt INTEGER,
    byte_snt NUMERIC(40,10),
    has_been_rd INTEGER,
    last_err_typ INTEGER,
    last_err_descr LONG VARCHAR,
    hash LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,fl_trans_run_id)
)
PARTITION BY COLUMN (fl_trans_run_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."FILE_TRANSFER_STAT"(
    fl_trans_stat_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    log_stmp LONG VARCHAR,
    tsk_id bigint,
    node INTEGER,
    nmnl_strt LONG VARCHAR,
    act LONG VARCHAR,
    src_host LONG VARCHAR,
    src_fl_full_nm LONG VARCHAR,
    src_fl_nm LONG VARCHAR,
    src_fl_nm_id LONG VARCHAR,
    src_stmp LONG VARCHAR,
    src_byte_snt NUMERIC(40,10),
    src_dur NUMERIC(40,10),
    tgt_host LONG VARCHAR,
    tgt_fl_full_nm LONG VARCHAR,
    tgt_fl_nm LONG VARCHAR,
    tgt_fl_nm_id LONG VARCHAR,
    tgt_byte_recv NUMERIC(40,10),
    tgt_dur NUMERIC(40,10),
    err_typ INTEGER,
    descr LONG VARCHAR,
    hash LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,fl_trans_stat_id)
)
PARTITION BY COLUMN (fl_trans_stat_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."GENERAL_LEDGER"(
    bill_ent_id bigint NOT NULL,
    gl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    gl_map_id bigint NOT NULL,
    dr_amt NUMERIC(18,4) NOT NULL,
    cr_amt NUMERIC(18,4) NOT NULL,
    post_dt DATE,
    crtd_dt DATE,
    je_num varchar(50),
    bene_pkg_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,gl_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."GROUP_RELATION"(
    grp_id bigint NOT NULL,
    grp_reln_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    grp_reln_typ_ref_id bigint NOT NULL,
    rltd_grp_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,grp_reln_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."INVOICE"(
    bill_ent_id bigint NOT NULL,
    inv_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pay_optn_ref_id bigint,
    init_flg SMALLINT,
    inv_num varchar(50),
    descr LONG VARCHAR,
    inv_amt NUMERIC(18,4) NOT NULL,
    min_due NUMERIC(18,4) NOT NULL,
    due_dt DATE,
    inv_dt DATE,
    cntc_id bigint,
    extnd_due_prd INTEGER,
    top_ent_schd_id bigint,
    cur_drct_bal NUMERIC(18,4) NOT NULL,
    cur_ssa_bal NUMERIC(18,4) NOT NULL,
    prior_drct_bal NUMERIC(18,4) NOT NULL,
    prior_ssa_bal NUMERIC(18,4) NOT NULL,
    add_ach_amt NUMERIC(18,4) NOT NULL,
    elig_expr_dt DATE,
    decd_cnt INTEGER,
    term_cnt INTEGER,
    cncl_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,inv_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LEP_APPEAL"(
    prsn_id bigint NOT NULL,
    lep_apl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    ext_apl_id varchar(50) NOT NULL,
    apl_dt DATE,
    rcv_dt DATE,
    apl_dcn varchar(50),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,lep_apl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LETTER"(
    prsn_id bigint NOT NULL,
    ltr_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,ltr_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LINE_ADDITIONAL_DIAGNOSIS"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    seq_num INTEGER NOT NULL,
    clm_add_diag_id bigint NOT NULL,
    ln_add_diag_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    diag_seq_num INTEGER,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,seq_num,clm_add_diag_id,ln_add_diag_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LINE_DISALLOW_EXPLANATION"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    seq_num INTEGER NOT NULL,
    ln_disallow_explain_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    disallow_amt NUMERIC(18,4),
    explain_cd_id bigint,
    disallow_explain_cd LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,seq_num,ln_disallow_explain_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LINE_PROCEDURE_MODIFIER"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    seq_num INTEGER NOT NULL,
    ln_pr_mod_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    mod_seq_num INTEGER,
    pr_mod_cd LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,seq_num,ln_pr_mod_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."MARX_CALENDAR"(
    marx_cal_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    pay_dt DATE,
    plan_dta_due_dt DATE,
    mo_rpt_rls_dt DATE,
    cert_of_enrl_dt DATE,
    strt_dt DATE,
    end_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (marx_cal_id)
)
PARTITION BY COLUMN (marx_cal_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."NOTE"(
    inq_id bigint NOT NULL,
    src_id bigint NOT NULL,
    src_typ_ref_id bigint NOT NULL,
    nte_ord INTEGER NOT NULL,
    nte_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    nte_typ_ref_id bigint,
    wrk_basket varchar(50),
    nte LONG VARCHAR,
    nte_ts TIMESTAMP,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id,src_id,src_typ_ref_id,nte_ord,nte_id)
)
PARTITION BY COLUMN (inq_id)
COLOCATE WITH (ODS.INQUIRY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ORGANIZATION_CODE"(
    org_id bigint NOT NULL,
    cd_val_id bigint NOT NULL,
    org_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,org_id,cd_val_id,org_cd_id)
)
PARTITION BY COLUMN (org_id)
COLOCATE WITH (ODS.ORGANIZATIONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."ORGANIZATION_CONTACT_TYPE"(
    org_id bigint NOT NULL,
    cntc_typ_ref_id bigint NOT NULL,
    org_cntc_typ_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,org_id,cntc_typ_ref_id,org_cntc_typ_id)
)
PARTITION BY COLUMN (org_id)
COLOCATE WITH (ODS.ORGANIZATIONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PAYMENT"(
    bill_ent_id bigint NOT NULL,
    pay_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pay_amt NUMERIC(18,4) NOT NULL,
    chk_num varchar(15),
    pay_snt_dt DATE,
    pay_src_ref_id bigint NOT NULL,
    refun_rsn_ref_id bigint NOT NULL,
    ent_bnk_acct_id bigint,
    cntc_id bigint,
    cncl_dt DATE,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,pay_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_COB"(
    prsn_id bigint NOT NULL,
    prsn_cob_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    act_typ_ref_id bigint,
    birth_dt DATE,
    gndr_cd char(1),
    ssn varchar(12),
    informant_reln_ref_id bigint,
    rcpt_method_ref_id bigint,
    rec_typ varchar(5) NOT NULL,
    rx_id varchar(20),
    rx_grp varchar(15),
    rx_bin varchar(15),
    rx_pcn varchar(15),
    rx_plan_phn varchar(100),
    cob_src varchar(5),
    seq_num varchar(3),
    msp_rsn_cd char(1),
    covrg_cd char(1),
    ind_plcy_num varchar(17),
    grp_plcy_num varchar(20),
    eff_dt DATE,
    expr_dt DATE,
    relshp_cd varchar(2),
    payr_id varchar(10),
    prsn_cd varchar(3),
    payr_ord varchar(3),
    emp_info_cd char(1),
    lead_contrc varchar(9),
    cls_act_typ varchar(2),
    wcsa_amt NUMERIC(12,2),
    wcsa_ind varchar(2),
    wcmsa_stlmnt_dt DATE,
    tot_rx_stlmnt_amt NUMERIC(12,2),
    is_rx_amt_incl char(1),
    term_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_cob_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_CODE"(
    prsn_id bigint NOT NULL,
    cd_val_id bigint NOT NULL,
    prsn_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,cd_val_id,prsn_cd_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_CONTACT"(
    prsn_id bigint NOT NULL,
    cntc_id bigint NOT NULL,
    prsn_cntc_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cntc_typ_ref_id bigint NOT NULL,
    cnfdt_flg SMALLINT,
    def_flg SMALLINT,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,cntc_id,prsn_cntc_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_LEP_EVENT"(
    prsn_id bigint NOT NULL,
    prsn_lep_evnt_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    lep_amt NUMERIC(14,2),
    tot_uncovered_mos INTEGER,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_lep_evnt_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_LEP_PROFILE"(
    prsn_id bigint NOT NULL,
    prsn_lep_prfl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_lep_prfl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_ORGANIZATION_RELATION"(
    prsn_id bigint NOT NULL,
    org_id bigint NOT NULL,
    prsn_org_reln_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    reln_typ_ref_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    src_sys_rec_id varchar(150),
    src_sys_ref_id varchar(10) NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    PRIMARY KEY (client_id,prsn_id,org_id,prsn_org_reln_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_PAYMENT_OPTIONS"(
    prsn_id bigint NOT NULL,
    prsn_pay_optn_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pay_optn_ref_id bigint NOT NULL,
    whld_typ_ref_id bigint,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_pay_optn_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_RELATION"(
    prsn_id bigint NOT NULL,
    rltd_prsn_id bigint NOT NULL,
    prsn_reln_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    reln_typ_ref_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,rltd_prsn_id,prsn_reln_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_ROLE"(
    prsn_id bigint NOT NULL,
    prsn_typ_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    prsn_typ_ref_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_typ_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_SUBSIDY_PROFILE"(
    prsn_id bigint NOT NULL,
    prsn_sbsdy_prfl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    sbsdy_typ_ref_id bigint NOT NULL,
    sbsdy_level_ref_id bigint,
    copay_cat_ref_id bigint,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_sbsdy_prfl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_WORK_ITEM"(
    prsn_id bigint NOT NULL,
    prsn_wrk_itm_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    wrk_ityp_ref_id bigint NOT NULL,
    add_dt DATE,
    proc_stat_ref_id bigint,
    proc_stat_dt DATE,
    prsn_evnt_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_wrk_itm_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PHONE"(
    cntc_id bigint NOT NULL,
    phn_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    area_cd varchar(3),
    loc_exch varchar(10),
    phn_num varchar(50),
    phn_ext varchar(10),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cntc_id,phn_id)
)
PARTITION BY COLUMN (cntc_id)
COLOCATE WITH (ODS.CONTACT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PLAN_MEMBERSHIPS"(
    prsn_id bigint NOT NULL,
    bene_grp_id bigint NOT NULL,
    plan_mbrshp_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    is_blbl SMALLINT,
    is_elig SMALLINT,
    elig_rsn_ref_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    PRIMARY KEY (client_id,prsn_id,bene_grp_id,plan_mbrshp_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."POS_CODE"(
    pos_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pos_cd LONG VARCHAR,
    pos_descr LONG VARCHAR,
    io_ind LONG VARCHAR,
    serv_cat_ref_id bigint,
    serv_grp_ref_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,pos_cd_id)
)
PARTITION BY COLUMN (pos_cd_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."POSTAL_ADDRESS"(
    cntc_id bigint NOT NULL,
    pstl_addr_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    str_ln1 varchar(100),
    str_ln2 varchar(100),
    str_ln3 varchar(100),
    cty varchar(75),
    cnty varchar(50),
    st varchar(50),
    pstl_cd varchar(20),
    cntry varchar(100),
    vldtd SMALLINT,
    vldtn_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cntc_id,pstl_addr_id)
)
PARTITION BY COLUMN (cntc_id)
COLOCATE WITH (ODS.CONTACT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PREMIUM"(
    grp_id bigint NOT NULL,
    prem_cat_id bigint NOT NULL,
    prem_rec_ord INTEGER NOT NULL,
    prem_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE NOT NULL,
    expr_dt DATE,
    prem_amt_rt NUMERIC(12,4),
    prem_ratio_fctr NUMERIC(12,4),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,prem_cat_id,prem_rec_ord,prem_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PROCEDURE_CODE"(
    pr_cd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pr_cd LONG VARCHAR,
    pr_descr LONG VARCHAR,
    std_ref_cd_1 LONG VARCHAR,
    std_ref_cd_2 LONG VARCHAR,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,pr_cd_id)
)
PARTITION BY COLUMN (pr_cd_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."RECEIPT"(
    bill_ent_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    rcpt_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    rcpt_typ_ref_id bigint NOT NULL,
    rcpt_amt NUMERIC(18,4) NOT NULL,
    acct_num varchar(50) NOT NULL,
    chk_num varchar(15),
    rcpt_dt DATE,
    prem_strt_dt DATE,
    prem_end_dt DATE,
    prd_mo_cnt INTEGER,
    post_dt DATE,
    confirm_num varchar(50),
    rcpt_stat_ref_id bigint NOT NULL,
    whld_typ_ref_id bigint NOT NULL,
    descr LONG VARCHAR,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,rcpt_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."REFERENCE_DATA"(
    ref_dta_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    ref_dmn varchar(50) NOT NULL,
    ref_cd varchar(30),
    descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    PRIMARY KEY (ref_dta_id,ref_dmn)
)
PARTITION BY COLUMN (ref_dta_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."RETURNED_MAIL"(
    rtrn_mail_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    prsn_id bigint,
    recv_dt DATE,
    doc_num varchar(50),
    rtrn_mail_typ_cd varchar(10),
    rtrn_rsn varchar(100),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,rtrn_mail_id)
)
PARTITION BY COLUMN (rtrn_mail_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."TOPIC"(
    inq_id bigint NOT NULL,
    tpc_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    case_id varchar(20),
    tpc_stat_ref_id bigint NOT NULL,
    tpc_sub_typ_ref_id bigint NOT NULL,
    tpc_typ_ref_id bigint NOT NULL,
    prsn_id bigint,
    descr LONG VARCHAR,
    dtl_descr LONG VARCHAR,
    end_tm TIMESTAMP,
    strt_tm TIMESTAMP,
    wrk_basket varchar(50),
    vld_frm_dt TIMESTAMP NOT NULL,
    insrt_usr varchar(50),
    upd_usr varchar(50),
    insrt_serv_rec_ts TIMESTAMP,
    upd_serv_rec_ts TIMESTAMP,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id,tpc_id)
)
PARTITION BY COLUMN (inq_id)
COLOCATE WITH (ODS.INQUIRY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_ACTIVITY"(
    um_rvw_id bigint NOT NULL,
    um_acty_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    usr_id LONG VARCHAR,
    crt_dt DATE,
    acty_rsn_ref_id bigint,
    cmplx_ind_ref_id bigint,
    um_serv_add INTEGER,
    um_inpt_add INTEGER,
    um_inpt_rvw_add INTEGER,
    um_nte_add INTEGER,
    rte_usr_id LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_acty_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_DIAGNOSIS_LINE"(
    um_rvw_id bigint NOT NULL,
    um_diag_set_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    diag_cd_id bigint,
    eff_dt DATE,
    sbmt_diag_cd_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_diag_set_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_DIAGNOSIS_SET"(
    um_rvw_id bigint NOT NULL,
    um_diag_set_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    crt_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_diag_set_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_INPATIENT"(
    um_rvw_id bigint NOT NULL,
    um_inpt_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    um_diag_set_id bigint,
    pre_auth_ind LONG VARCHAR,
    ref_ind LONG VARCHAR,
    care_typ_ind LONG VARCHAR,
    usr_id LONG VARCHAR,
    crt_dt DATE,
    rcv_dt DATE,
    nxt_rvw_dt DATE,
    aprv_dt DATE,
    facil_prvd_id bigint,
    facil_addr_typ_cd LONG VARCHAR,
    admt_prvd_id bigint,
    atnd_prvd_id bigint,
    surg_prvd_id bigint,
    surg_addr_typ_cd LONG VARCHAR,
    pcp_prvd_id bigint,
    rqst_prvd_id bigint,
    rqst_addr_typ_cd LONG VARCHAR,
    ptnt_num LONG VARCHAR,
    med_rls_ind LONG VARCHAR,
    facil_ntwk_stat LONG VARCHAR,
    out_of_area_ind LONG VARCHAR,
    admt_trmt_typ LONG VARCHAR,
    cur_trmt_typ LONG VARCHAR,
    pr_cd_id bigint,
    diag_cd_id bigint,
    rltd_diag_cd_id bigint,
    admt_pr_cd_id bigint,
    admt_diag_cd_id bigint,
    admt_rltd_diag_cd_id bigint,
    rqst_dt_of_surg DATE,
    auth_dt_of_surg DATE,
    rqst_sec_opn_ind LONG VARCHAR,
    obtained_sec_opn_ind LONG VARCHAR,
    rqst_pre_oprn_days INTEGER,
    auth_pre_oprn_days INTEGER,
    norm_pre_oprn_days INTEGER,
    pre_oprn_rsn_ref_id bigint,
    rqst_pos_cd_id bigint,
    auth_pos_cd_id bigint,
    pos_norm_ind LONG VARCHAR,
    pos_rsn_ref_id bigint,
    denial_rsn_ref_id bigint,
    denial_usr_id LONG VARCHAR,
    disallow_explain_id bigint,
    prd_vio_ind LONG VARCHAR,
    prd_vio_rsn_ref_id bigint,
    rqst_stay_len INTEGER,
    auth_stay_len INTEGER,
    admt_stay_len_frm INTEGER,
    admt_stay_len_to INTEGER,
    stay_len_frm INTEGER,
    stay_len_to INTEGER,
    actl_stay_len INTEGER,
    birth_wgt INTEGER,
    rqst_admt_dt DATE,
    auth_admt_dt DATE,
    actl_admt_dt DATE,
    admt_nte_dt DATE,
    admt_dt_rsn_ref_id bigint,
    rqst_we_admt_ind LONG VARCHAR,
    auth_we_admt_ind LONG VARCHAR,
    we_admt_rsn_ref_id bigint,
    expected_dischrg_dt DATE,
    dischrg_stat LONG VARCHAR,
    dischrg_diag_id bigint,
    dischrg_dt DATE,
    dischrg_nte_dt DATE,
    rqst_prvd_pcp_ind LONG VARCHAR,
    denial_dt DATE,
    prvd_compl_ind LONG VARCHAR,
    prvd_non_compl_rsn_ref_id bigint,
    rqst_chrg_amt INTEGER,
    tot_amt INTEGER,
    pd_stay_len INTEGER,
    alwd_stay_len INTEGER,
    caller_typ_ref_id bigint,
    pre_auth_pr_ind LONG VARCHAR,
    pre_auth_diag_ind char(1),
    pre_auth_facil_ind LONG VARCHAR,
    case_mgmt_pr_ind LONG VARCHAR,
    case_mgmt_diag_ind char(1),
    hm_hlth_care_ind LONG VARCHAR,
    microfilm_id LONG VARCHAR,
    glbl_case_rt_ind LONG VARCHAR,
    out_of_area_cmpnt_ind LONG VARCHAR,
    serv_area_ind LONG VARCHAR,
    co_mgmt_obtained_ind LONG VARCHAR,
    serv_cat LONG VARCHAR,
    risk_ind LONG VARCHAR,
    risk_delegated_ent_id LONG VARCHAR,
    clm_delegated_ent_ind LONG VARCHAR,
    clm_delegated_ent_id LONG VARCHAR,
    um_delegated_ent_ind LONG VARCHAR,
    um_delegated_ent_id LONG VARCHAR,
    admt_sbmt_diag_id bigint,
    rltd_sbmt_diag_id bigint,
    pri_sbmt_diag_id bigint,
    rltd_sbmt_pri_diag_id bigint,
    sbmt_dischrg_diag_id bigint,
    pri_diag_trnsltn_ind LONG VARCHAR,
    dischrg_diag_trnsltn_ind LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_inpt_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_SERVICE"(
    um_rvw_id bigint NOT NULL,
    um_serv_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    prsn_id bigint,
    pre_auth_ind LONG VARCHAR,
    ref_ind LONG VARCHAR,
    serv_typ LONG VARCHAR,
    serv_cat LONG VARCHAR,
    usr_id LONG VARCHAR,
    crt_dt DATE,
    rcv_dt DATE,
    nxt_rvw_dt DATE,
    auth_dt DATE,
    serv_stat_cd LONG VARCHAR,
    serv_stat_dt DATE,
    stat_seq_num INTEGER,
    serv_frm_dt DATE,
    serv_to_dt DATE,
    requesting_prvd_id bigint,
    srvc_prvd_id bigint,
    facil_prvd_id bigint,
    pcp_prvd_id bigint,
    med_rls_ind LONG VARCHAR,
    diag_cd_id bigint,
    rltd_diag_cd_id bigint,
    sbmt_rltd_diag_cd_id bigint,
    sbmt_diag_cd_id bigint,
    rqst_pos_cd_id bigint,
    auth_pos_cd_id bigint,
    pos_rsn_referense_id bigint,
    out_of_area_ind LONG VARCHAR,
    referal_typ_ref_id bigint,
    serv_cd LONG VARCHAR,
    serv_rule_cd LONG VARCHAR,
    serv_prc_cd LONG VARCHAR,
    serv_grp_cd LONG VARCHAR,
    pr_cd_id bigint,
    rqst_unt INTEGER,
    auth_unt INTEGER,
    unt_differ_reson_ref_id bigint,
    rqst_chrg NUMERIC(14,2),
    contr_amt NUMERIC(14,2),
    negotiate_amt NUMERIC(14,2),
    negotiate_pct NUMERIC(14,2),
    fee_rsn_ref_id bigint,
    prc_amt NUMERIC(14,2),
    prc_explain_id bigint,
    disallow_explain_id bigint,
    serv_denial_rsn_ref_id bigint,
    denial_usr_id LONG VARCHAR,
    auth_svind LONG VARCHAR,
    auth_pr_ind LONG VARCHAR,
    auth_diag_ind LONG VARCHAR,
    auth_prvd_ind LONG VARCHAR,
    case_mgmt_svind LONG VARCHAR,
    case_mgmt_pr_ind LONG VARCHAR,
    case_mgmt_diag_ind LONG VARCHAR,
    prd_vio_ind LONG VARCHAR,
    prd_vio_rsn_ref_id bigint,
    compl_ind LONG VARCHAR,
    compl_vio_rsn_ref_id bigint,
    asst_surg_ind_1 LONG VARCHAR,
    rqst_sec_opn_ind LONG VARCHAR,
    obtained_sec_opn_ind LONG VARCHAR,
    asst_surg_ind_2 LONG VARCHAR,
    inp_usr_site_cd LONG VARCHAR,
    pcp_ind LONG VARCHAR,
    alwd_amt NUMERIC(14,2),
    alwd_unt INTEGER,
    use_amt NUMERIC(14,2),
    use_unt INTEGER,
    denial_dt DATE,
    "Provider Network Id" bigint,
    prvd_ntwk_id LONG VARCHAR,
    prvd_agree_id LONG VARCHAR,
    clin_edit_ind LONG VARCHAR,
    clin_edit_typ LONG VARCHAR,
    clin_edit_fmt_ind LONG VARCHAR,
    clin_edit_seq_num INTEGER,
    caller_typ_ref_id bigint,
    asst_surg_rsn_ref_id bigint,
    microfilm_id LONG VARCHAR,
    pay_area_ind LONG VARCHAR,
    serv_area_ind LONG VARCHAR,
    risk_delegated_ind LONG VARCHAR,
    risk_delegated_ent_id LONG VARCHAR,
    clm_delegated_ind LONG VARCHAR,
    clm_delegated_ent_id LONG VARCHAR,
    um_delegated_ind LONG VARCHAR,
    um_delegated_ent_id LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_serv_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UNAPPLIED_CASH"(
    unapp_csh_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    err_typ_ref_id bigint,
    stat_ref_id bigint,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    cncl_dt DATE,
    err_descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,unapp_csh_id)
)
PARTITION BY COLUMN (unapp_csh_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BANK_ACCOUNT"(
    bnk_org_id bigint NOT NULL,
    bnk_id bigint NOT NULL,
    bnk_acct_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    acct_nm varchar(100),
    acct_num varchar(50) NOT NULL,
    acct_typ_ref_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bnk_org_id,bnk_id,bnk_acct_id)
)
PARTITION BY COLUMN (bnk_org_id)
COLOCATE WITH (ODS.BANK)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BENEFIT_PACKAGE_RELATION"(
    bene_pkg_id bigint NOT NULL,
    pkg_reln_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    pkg_reln_typ_ref_id bigint NOT NULL,
    rltd_bene_pkg_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bene_pkg_id,pkg_reln_id)
)
PARTITION BY COLUMN (bene_pkg_id)
COLOCATE WITH (ODS.BENEFIT_PACKAGE)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_ENTITY_CONTACT"(
    bill_ent_id bigint NOT NULL,
    cntc_id bigint NOT NULL,
    bill_ent_cntc_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cntc_typ_ref_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    PRIMARY KEY (client_id,bill_ent_id,cntc_id,bill_ent_cntc_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_ENTITY_DETAIL"(
    bill_ent_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    client_id bigint NOT NULL,
    ver bigint NOT NULL,
    fin_resp_ref_id bigint NOT NULL,
    grp_id bigint NOT NULL,
    is_grp_stmt SMALLINT,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."BILLING_ENTITY_SCHEDULE"(
    bill_ent_id bigint NOT NULL,
    bill_schd_id bigint NOT NULL,
    bill_ent_schd_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    whld_typ_ref_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,bill_schd_id,bill_ent_schd_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CHECK_STATUS"(
    clm_pay_id bigint NOT NULL,
    chk_id bigint NOT NULL,
    chk_stat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    stat_seq_num INTEGER,
    chk_stat LONG VARCHAR,
    chk_stat_rsn LONG VARCHAR,
    stat_dt DATE,
    usr_id LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,clm_pay_id,chk_id,chk_stat_id)
)
PARTITION BY COLUMN (clm_pay_id)
COLOCATE WITH (ODS.CLAIM_PAYMENT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_ADDITIONAL_DIAGNOSIS"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    clm_add_diag_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    client_id bigint NOT NULL,
    ver bigint NOT NULL,
    diag_cd_id bigint NOT NULL,
    trnslt_diag_cd_id bigint,
    sbmt_diag_cd_id bigint,
    prsnt_on_adm_ind LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,clm_add_diag_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_DETAIL"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    seq_num INTEGER NOT NULL,
    clm_dtl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    ln_of_bus LONG VARCHAR,
    ln_of_bus_ind LONG VARCHAR,
    cap_fnd_id LONG VARCHAR,
    cap_pool_id LONG VARCHAR,
    pos_cd_id bigint,
    pr_cd_id bigint,
    diag_cd_id bigint,
    rltd_diag_cd_id bigint,
    cur_clm_stat_cd LONG VARCHAR,
    serv_frm_dt DATE,
    serv_to_dt DATE,
    rm_typ_id LONG VARCHAR,
    clm_chrg_amt NUMERIC(40,10),
    anes_mod LONG VARCHAR,
    clm_rt_amt NUMERIC(40,10),
    alwd_amt NUMERIC(40,10),
    considered_amt NUMERIC(40,10),
    num_of_unt INTEGER,
    alwd_num_of_unt INTEGER,
    deductable_amt NUMERIC(40,10),
    copay_amt NUMERIC(40,10),
    coinsurance_amt NUMERIC(40,10),
    risk_whld_amt NUMERIC(40,10),
    clm_pd_amt NUMERIC(40,10),
    disallow_amt NUMERIC(40,10),
    explain_cd_id bigint,
    disallow_explain_cd bigint,
    agree_prc NUMERIC(40,10),
    disc_amt NUMERIC(40,10),
    suppl_disc_amt NUMERIC(40,10),
    its_disc_amt NUMERIC(40,10),
    prvd_ntwk_stat LONG VARCHAR,
    ref_ind LONG VARCHAR,
    pre_auth_ind LONG VARCHAR,
    capitated_svind LONG VARCHAR,
    subs_pay NUMERIC(40,10),
    prvd_pay NUMERIC(40,10),
    pre_pd_amt NUMERIC(40,10),
    serv_rpt_cat LONG VARCHAR,
    exper_cat LONG VARCHAR,
    acct_cat LONG VARCHAR,
    ref_id LONG VARCHAR,
    ref_seq_num INTEGER,
    pre_auth_id LONG VARCHAR,
    pre_auth_seq_num INTEGER,
    pre_auth_src LONG VARCHAR,
    io_ind LONG VARCHAR,
    ambul_pay_cd LONG VARCHAR,
    ambul_pay_stat LONG VARCHAR,
    clm_837_seq_num INTEGER,
    med_util_edit_ind LONG VARCHAR,
    sbmt_diag_cd bigint,
    sbmt_rltd_diag_cd bigint,
    trnslt_diag_cd bigint,
    trnslt_rltd_diag_cd bigint,
    prvd_specialty bigint,
    prvd_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,seq_num,clm_dtl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_PAYMENT_DETAIL"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    clm_pay_id bigint NOT NULL,
    clm_pay_dtl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    ln_of_bus bigint,
    orig_amt NUMERIC(18,4),
    eob_flg LONG VARCHAR,
    vio_flg LONG VARCHAR,
    ntwk_flg LONG VARCHAR,
    prompt_pay_disc NUMERIC(18,4),
    disc_pct NUMERIC(18,4),
    prior_pd_amt NUMERIC(18,4),
    clm_pay_net_amt NUMERIC(18,4),
    prompt_pay_cd LONG VARCHAR,
    ovrd_flg LONG VARCHAR,
    int_amt NUMERIC(18,4),
    calc_int NUMERIC(18,4),
    reimb_amt NUMERIC(18,4),
    prior_reimb NUMERIC(18,4),
    confidential_flg LONG VARCHAR,
    allowable_amt NUMERIC(18,4),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,clm_pay_id,clm_pay_dtl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_REDUCTION_DETAIL"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    clm_pay_rdctn_id bigint NOT NULL,
    clm_rdctn_dtl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    payee_typ LONG VARCHAR,
    prvd_id bigint,
    subs_id bigint,
    crt_dt DATE,
    orig_amt NUMERIC(18,4),
    auto_pay_rdctn_flg LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,clm_pay_rdctn_id,clm_rdctn_dtl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_REDUCTION_HISTORY"(
    clm_pay_rdctn_id bigint NOT NULL,
    clm_rdctn_hist_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    rdctn_evnt_typ LONG VARCHAR,
    clm_pay_id bigint,
    rec_dt DATE,
    prd_end_dt DATE,
    rdctn_amt NUMERIC(18,4),
    usr_id LONG VARCHAR,
    rdctn_rsn LONG VARCHAR,
    chk_num LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,clm_pay_rdctn_id,clm_rdctn_hist_id)
)
PARTITION BY COLUMN (clm_pay_rdctn_id)
COLOCATE WITH (ODS.CLAIM_PAYMENT_REDUCTION)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CLAIM_STATUS"(
    prsn_id bigint NOT NULL,
    clm_id bigint NOT NULL,
    seq_num INTEGER NOT NULL,
    clm_stat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    clm_stat_cd LONG VARCHAR,
    cur_its_stat_cd LONG VARCHAR,
    clm_stat_ts TIMESTAMP,
    stat_rsn_ref_id bigint,
    usr_id LONG VARCHAR,
    routed_usr_id LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,clm_id,seq_num,clm_stat_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."COMPLAINT_STATUS"(
    inq_id bigint NOT NULL,
    complaint_id bigint NOT NULL,
    complaint_stat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    rej_rsn_ref_id bigint,
    complaint_stat_ref_id bigint NOT NULL,
    complaint_stat_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,inq_id,complaint_id,complaint_stat_id)
)
PARTITION BY COLUMN (inq_id)
COLOCATE WITH (ODS.INQUIRY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."CONTACT_TYPE_CONTACT"(
    cntc_id bigint NOT NULL,
    org_cntc_typ_id bigint NOT NULL,
    cntc_typ_cntc_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cntc_id,org_cntc_typ_id,cntc_typ_cntc_id)
)
PARTITION BY COLUMN (cntc_id)
COLOCATE WITH (ODS.CONTACT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."EXHIBIT_GROUP"(
    exhibit_grp_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    bene_grp_id bigint,
    triggering_exhibit_id bigint NOT NULL,
    lang_ref_id bigint,
    suppressed_flg SMALLINT,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,exhibit_grp_id)
)
PARTITION BY COLUMN (exhibit_grp_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."EXHIBIT_GROUP_EXHIBIT"(
    exhibit_id bigint NOT NULL,
    exhibit_grp_id bigint NOT NULL,
    exhibit_grp_exhibit_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    cmpnt_num varchar(10),
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,exhibit_id,exhibit_grp_id,exhibit_grp_exhibit_id)
)
PARTITION BY COLUMN (exhibit_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."GENERAL_LEDGER_MAP"(
    gl_map_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    cr_acct_ref_id bigint NOT NULL,
    dr_acct_ref_id bigint NOT NULL,
    gl_map_typ_ref_id bigint NOT NULL,
    gl_map_nm varchar(50),
    descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (gl_map_id)
)
PARTITION BY COLUMN (gl_map_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."INVOICE_DETAIL"(
    bill_ent_id bigint NOT NULL,
    inv_id bigint NOT NULL,
    inv_dtl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    ent_schd_strt_dt DATE,
    ent_schd_end_dt DATE,
    bnfc_id bigint,
    whld_typ_ref_id bigint,
    dtl_typ_ref_id bigint,
    bnfc_reln_ref_id bigint,
    inv_dtl_amt NUMERIC(18,4) NOT NULL,
    cur_flg SMALLINT,
    cr_flg SMALLINT,
    bene_grp_id bigint,
    src_typ_ref_id bigint,
    bill_src_id bigint,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,inv_id,inv_dtl_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."INVOICE_STATUS"(
    bill_ent_id bigint NOT NULL,
    inv_id bigint NOT NULL,
    inv_stat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    inv_stat_dt DATE,
    inv_stat_ref_id bigint NOT NULL,
    descr LONG VARCHAR,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,bill_ent_id,inv_id,inv_stat_id)
)
PARTITION BY COLUMN (bill_ent_id)
COLOCATE WITH (ODS.BILLING_ENTITY)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LEP_APPEAL_DECISION"(
    prsn_id bigint NOT NULL,
    lep_apl_id bigint NOT NULL,
    lep_apl_dec bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    apl_dec_dt DATE,
    lep_apl_dec_ref_id bigint NOT NULL,
    rcv_dt DATE,
    mail_notice_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,lep_apl_id,lep_apl_dec)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LETTER_DETAIL"(
    prsn_id bigint NOT NULL,
    ltr_id bigint NOT NULL,
    ltr_dtl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,ltr_id,ltr_dtl_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LETTER_JOB"(
    prsn_id bigint NOT NULL,
    ltr_dtl_id bigint NOT NULL,
    ltr_job_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    src_ref_id bigint,
    ltr_src_num varchar(50),
    qa_dt DATE,
    inbound_src_ref_id bigint,
    ltr_inbound_src_num varchar(50),
    pg_cnt INTEGER,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,ltr_dtl_id,ltr_job_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LETTER_REGISTER"(
    prsn_id bigint NOT NULL,
    ltr_id bigint NOT NULL,
    ltr_rgstr_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    exhibit_id bigint NOT NULL,
    rqst_dt DATE,
    tgr_dt DATE,
    prt_dt DATE,
    mail_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,ltr_id,ltr_rgstr_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."LETTER_WORK_ITEM"(
    prsn_id bigint NOT NULL,
    ltr_rgstr_id bigint NOT NULL,
    prsn_wrk_itm_id bigint NOT NULL,
    ltr_wrk_itm_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    wrk_itm_exibit_eff_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,ltr_rgstr_id,prsn_wrk_itm_id,ltr_wrk_itm_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_EVENT_ATTRIBUTE"(
    prsn_evnt_id bigint NOT NULL,
    prsn_evnt_attr_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    attr_typ_ref_id bigint NOT NULL,
    seq_evnt_num INTEGER,
    nmrc_evnt_attr NUMERIC(23,4),
    txt_evnt_attr LONG VARCHAR,
    ts_evnt_attr TIMESTAMP,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    PRIMARY KEY (client_id,prsn_evnt_id,prsn_evnt_attr_id)
)
PARTITION BY COLUMN (prsn_evnt_id)
COLOCATE WITH (ODS.PERSON_EVENT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_EVENT_STATUS"(
    prsn_evnt_id bigint NOT NULL,
    prsn_evnt_stat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    stat_ref_id bigint NOT NULL,
    evnt_stat_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_evnt_id,prsn_evnt_stat_id)
)
PARTITION BY COLUMN (prsn_evnt_id)
COLOCATE WITH (ODS.PERSON_EVENT)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_EVENT_STATUS_REASON"(
    prsn_evnt_stat_id bigint NOT NULL,
    prsn_evnt_stat_rsn_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    rsn_ref_id bigint NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    PRIMARY KEY (client_id,prsn_evnt_stat_id,prsn_evnt_stat_rsn_id)
)
PARTITION BY COLUMN (prsn_evnt_stat_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PERSON_LEP_PROFILE_RECORD"(
    prsn_id bigint NOT NULL,
    prsn_lep_prfl_id bigint NOT NULL,
    prsn_lep_prfl_rec_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    lep_rec_typ_ref_id bigint NOT NULL,
    creditable_covrg_flg SMALLINT,
    incr_uncovered_mos INTEGER,
    prior_plan_uncovered_mos INTEGER,
    attest_rspns_typ_ref_id bigint,
    elig_strt_dt DATE,
    end_of_iep DATE,
    gap_strt_dt DATE,
    gap_end_dt DATE,
    beq_rspns_dt DATE,
    rspns_to_attest_dt DATE,
    lep_cms_confirm_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,prsn_id,prsn_lep_prfl_id,prsn_lep_prfl_rec_id)
)
PARTITION BY COLUMN (prsn_id)
COLOCATE WITH (ODS.PERSONS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PREMIUM_CATEGORY"(
    grp_id bigint NOT NULL,
    prem_cat_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    prem_tbl_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,prem_cat_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PREMIUM_PART"(
    grp_id bigint NOT NULL,
    prem_part_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    prem_id bigint,
    sbsdy_level_ref_id bigint,
    resp_prty_ref_id bigint NOT NULL,
    splt_method_ref_id bigint NOT NULL,
    prem_part_amt NUMERIC(19,4),
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,prem_part_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."PREMIUM_TABLE"(
    grp_id bigint NOT NULL,
    bene_grp_id bigint NOT NULL,
    prem_tbl_id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    prem_typ_ref_id bigint NOT NULL,
    eff_dt DATE,
    expr_dt DATE,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,grp_id,bene_grp_id,prem_tbl_id)
)
PARTITION BY COLUMN (grp_id)
COLOCATE WITH (ODS.GROUPS)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."TOPIC_COMMUNICATION"(
    cmcn_inq_id bigint NOT NULL,
    tpc_inq_id bigint NOT NULL,
    cmcn_id bigint NOT NULL,
    tpc_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    insrt_usr varchar(50),
    upd_usr varchar(50),
    insrt_serv_rec_ts TIMESTAMP,
    upd_serv_rec_ts TIMESTAMP,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id varchar(10) NOT NULL,
    src_sys_rec_id varchar(150),
    PRIMARY KEY (client_id,cmcn_inq_id,tpc_inq_id,cmcn_id,tpc_id)
)
PARTITION BY COLUMN (cmcn_inq_id)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_INPATIENT_REVIEW"(
    um_rvw_id bigint NOT NULL,
    um_inpt_rvw_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    um_diag_set_id bigint,
    crt_dt DATE,
    trmt_typ LONG VARCHAR,
    rvw_mthd_ref_id bigint,
    rqst_stay_len INTEGER,
    auth_stay_len INTEGER,
    stay_len_rsn_ref_id bigint,
    regn_stay_len INTEGER,
    avg_stay_len INTEGER,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    src_sys_rec_id LONG VARCHAR,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_inpt_rvw_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_INPATIENT_STATUS"(
    um_rvw_id bigint NOT NULL,
    um_inpt_stat bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    usr_id LONG VARCHAR,
    um_inpt_stat_cd LONG VARCHAR,
    crt_dt DATE,
    um_stat_rsn_ref_id bigint,
    src_sys_rec_id LONG VARCHAR,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_inpt_stat)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
Create table ODS."UM_SERVICE_OVERRIDE"(
    um_rvw_id bigint NOT NULL,
    um_serv_id bigint NOT NULL,
    um_serv_ovrd_id bigint NOT NULL,
    ver bigint NOT NULL,
    client_id bigint NOT NULL,
    seq_num INTEGER,
    ovrd_ind LONG VARCHAR,
    ovrd_amt NUMERIC(14,2),
    ovrd_val LONG VARCHAR,
    ovrd_dt DATE,
    explain_cd_id bigint,
    usr_id LONG VARCHAR,
    src_sys_rec_id LONG VARCHAR,
    src_sys_ref_id LONG VARCHAR NOT NULL,
    vld_frm_dt TIMESTAMP NOT NULL,
    vld_to_dt TIMESTAMP,
    oprn LONG VARCHAR,
    PRIMARY KEY (client_id,um_rvw_id,um_serv_id,um_serv_ovrd_id)
)
PARTITION BY COLUMN (um_rvw_id)
COLOCATE WITH (ODS.UM_REVIEW)
REDUNDANCY 1
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT 'DISK_STORE' ASYNCHRONOUS;
