CREATE DISKSTORE STORE1 
    MAXLOGSIZE 1024 
    AUTOCOMPACT TRUE
    ALLOWFORCECOMPACTION  FALSE 
    COMPACTIONTHRESHOLD  70
    TIMEINTERVAL  100000
    WRITEBUFFERSIZE 2000000
    QUEUESIZE 10000
    ('/gemfire-store/');
    
    
  
 
 DROP SCHEMA  IF EXISTS ODS RESTRICT;
 create schema ODS default server groups(GemfireAll);