
SYS.CREATE_ALL_BUCKETS('adjustment');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'adjustment',
'BILL_ENT_ID,ADJ_ID,VER,CLIENT_ID,ADJ_TYP_REF_ID,IS_CR_ADJ,BILL_ENT_SCHD_ID,ADJ_AMT,DESCR,POST_DT,ORIG_RCPT_ID,NSF_RSN_REF_ID,WHLD_TYP_REF_ID,SRC_TYP_REF_ID,BILL_SRC_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/adjustment.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);

SYS.CREATE_ALL_BUCKETS('bank');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'bank',
'BNK_ORG_ID,BNK_ID,VER,CLIENT_ID,BNK_FULL_NM,RTNG_NUM,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/bank.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('benefit_group_name');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'benefit_group_name',
'GRP_ID,BENE_GRP_ID,BENE_GRP_NM_ID,VER,CLIENT_ID,BENE_GRP_NM,DESCR,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/benefit_group_name.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('benefit_groups');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'benefit_groups',
'GRP_ID,BENE_PKG_ID,BENE_GRP_ID,VER,CLIENT_ID,BENE_GRP_CD,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/benefit_groups.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('benefit_package');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'benefit_package',
'BENE_PKG_ID,VER,CLIENT_ID,BENE_PKG_CD,BENE_PKG_TYP_REF_ID,ORG_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/benefit_package.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_entity');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_entity',
'BILL_ENT_ID,VER,CLIENT_ID,BILL_ENT_REF_ID,GRP_ID,PRSN_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_entity.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_reconciliation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_reconciliation',
'BILL_ENT_ID,BILL_RECON_ID,VER,CLIENT_ID,CR_TYP_REF_ID,CR_SRC_ID,DR_TYP_REF_ID,DR_SRC_ID,AMT,CNCL_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_reconciliation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_schedule');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_schedule',
'BILL_SCHD_ID,VER,CLIENT_ID,ACCT_PRD_STRT,ACCT_PRD_END,PRD_MO_CNT,BILL_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_schedule.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_source');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_source',
'BILL_ENT_ID,SRC_TYP_REF_ID,BILL_SRC_ID,CLIENT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_source.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('charge_item');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'charge_item',
'BILL_ENT_ID,PREM_PART_ID,BILL_ENT_SCHD_ID,CHRG_ITM_ID,VER,CLIENT_ID,CHRG_ITYP_REF_ID,CHRG_ITM_AMT,POST_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/charge_item.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('check');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'check',
'CLM_PAY_ID,CHK_ID,VER,CLIENT_ID,CHK_SEQ_NUM,CHK_NUM,PAYEE_ID,CASHED_DT,REISSUED_DT,PRNT_DT,CHK_TYP,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/check.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim',
'PRSN_ID,CLM_ID,VER,CLIENT_ID,SUBS_ID,SERVICING_PRVD_ID,BENE_GRP_ID,CLM_TYP_REF_ID,CLM_SUB_TYP_REF_ID,CLM_RCV_DT,CLM_INP_DT,LAST_ACT_TS,CLM_PD_DT,NXT_RVW_DT,SERV_FRM_DT,SERV_TO_DT,PAYEE_PRVD_ID,CLM_RLS_IND,CUR_ILLNESS_DT,SIMILLAR_ILLNESS_DT,PCP_ID,REFNG_PRVD_ID,PRE_AUTH_NUM,PAY_CALC_DT,CLM_AI_EOB_IND,EXPLAIN_CD_ID,IMG_ADDR,UNABLE_TO_WRK_FRM,UNABLE_TO_WRK_TO,HOSP_FRM,HOSP_TO,LAB_SVIND,MDCR_RE_SUBM_NUM,OUT_OF_AREA_IND,XRAY_IND,CLM_RECORDS_IND,CLM_PROC_DT,CRTD_FRM_CLM_ID,ADJ_TO_CLM_ID,ADJ_FRM_CLM_ID,NTWK_PRVD_ENT_PRFX,NTWK_PRVD_PRFX,NTWK_PRVD_CAP_PRFX,NON_PARTIC_PRVD_PRFX,SERV_DEF_PRFX,PRVD_ACCUM_PRFX,PRCS_CTRL_AGNT_PRFX,MOD_PRC_RULES_PRFX,PRVD_NTWK_ID,PRVD_AGREE_ID,MDCR_ASSIGN_IND,PAY_PRVD_IND,OTH_BENE_IND,ACDT_IND,ACDT_ST,ACDT_DT,ACDT_AMT,PTNT_ACCT_NUM,PTNT_PD_AMT,CLM_TOT_CHRG,CLM_TOT_PAY,CHK_CYCLE_OVRD_IND,CLM_INP_METHOD,CLM_AUD_IND,EXT_REF_IND,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('client_reference_data');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'client_reference_data',
'CLIENT_REF_DTA_ID,VER,CLIENT_ID,CMN_REF_DTA_ID,REF_ENT,REF_DMN,REF_CD,REF_DESCR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/client_reference_data.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('clients');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'clients',
'CLIENT_ID,VER,FULL_CLIENT_SYS_CD,CLIENT_SYS_CD,CLIENT_LGCY_CD,CLIENT_ACRONYM,IMPL_STRT_DT,GO_LVE_DT,ENV_CD,MAIN_APP_CD,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/clients.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('cob_claim_diagnosis');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'cob_claim_diagnosis',
'PRSN_ID,PRSN_COB_ID,REC_ORD,VER,CLIENT_ID,DIAG_IND,CLM_DIAG_CD,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/cob_claim_diagnosis.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('cob_organization_person');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'cob_organization_person',
'PRSN_ID,PRSN_COB_ID,ORG_PRSN_TYP_REF_ID,VER,CLIENT_ID,ORG_NM,FIRST_NM,MID_NM,LAST_NM,EMPR_TAX_ID,SSN,STR_LN1,STR_LN2,CTY,ST,PSTL_CD,PHN_NUM,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/cob_organization_person.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('code_value');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'code_value',
'CD_VAL_ID,VER,CLIENT_ID,CD_VAL,CD_TYP_REF_ID,SRC_SYS_REF_ID,SRC_SYS_REC_ID,VLD_FRM_DT,VLD_TO_DT,DEL',
null,
'/gemfire-logs/done/code_value.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('communication');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'communication',
'INQ_ID,CMCN_ID,VER,CLIENT_ID,TRACK_NUM,CNTC_ID,FIRST_NM,LAST_NM,PHN_NUM,STRT_TM,END_TM,PRSN_ID,INSRT_USR,UPD_USR,INSRT_SERV_REC_TS,UPD_SERV_REC_TS,PRSN_EVNT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/communication.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('complaint');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'complaint',
'INQ_ID,COMPLAINT_ID,VER,CLIENT_ID,COMPLAINT_SUB_TYP_REF_ID,COMPLAINT_TYP_REF_ID,PRSN_ID,AOR_PRSN_ID,TRACK_NUM,CASE_ID,EXPD,EXPD_DESCR,FILLING_TYP_REF_ID,COMPLAINT_DESCR,RTS_OFFR,RTS_PROVIDED,INFO_PROVIDED_TO_CALLER,RCPT_METHOD_REF_ID,CASE_CRTD,DUE_DT,EXT_DT,EXT_RSN,CLOSE_DT,DRUG_DOSAGE,DRUG_NM,DRUG_QTY,PRESCRIBING_PHYSN_NM,PRESCRIBING_PHYSN_PHN,PRESCRIBING_PHYSN_FAX,RSLVD_ON_CALL,IMG_RECV_DT,COOR_USR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/complaint.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('contact');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'contact',
'CNTC_ID,VER,CLIENT_ID,CNTC_TYP_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/contact.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('diagnosis_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'diagnosis_code',
'DIAG_CD_ID,VER,CLIENT_ID,DIAG_CD,DIAG_DESCR,RLTD_DIAG_CD,STD_REF_CD_1,STD_REF_CD_2,DIAG_TYP,EXPR_DT,EFF_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/diagnosis_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('electronic_address');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'electronic_address',
'CNTC_ID,ELEC_ADDR_ID,VER,CLIENT_ID,ELEC_ADDR,ADDR_FMT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/electronic_address.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('entity_bank_account');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'entity_bank_account',
'BILL_ENT_ID,BNK_ACCT_ID,ENT_BNK_ACCT_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/entity_bank_account.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('exhibit');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'exhibit',
'EXHIBIT_ID,VER,CLIENT_ID,EXHIBIT_CD_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/exhibit.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('explanation_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'explanation_code',
'EXPLAIN_CD_ID,VER,CLIENT_ID,EXPLAIN_TYP,EXPLAIN_STAT,SD,LD_1,LD_2,EXPLAIN_LBLTY_IND,EDI_CLM_STAT_CAT,EDI_CLM_STAT,EDI_CLM_ADJ_RSN,REM_RMRK,PRVD_ADJ_RSN,HC_PLCY_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/tmp/data/explanation_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('general_ledger');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'general_ledger',
'BILL_ENT_ID,GL_ID,VER,CLIENT_ID,SRC_TYP_REF_ID,BILL_SRC_ID,GL_MAP_ID,DR_AMT,CR_AMT,POST_DT,CRTD_DT,JE_NUM,BENE_PKG_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/general_ledger.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('group_relation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'group_relation',
'GRP_ID,GRP_RELN_ID,VER,CLIENT_ID,GRP_RELN_TYP_REF_ID,RLTD_GRP_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/group_relation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('groups');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'groups',
'GRP_ID,VER,CLIENT_ID,GRP_CD,GRP_TYP_REF_ID,ORG_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/groups.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('inquiry');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'inquiry',
'INQ_ID,VER,CLIENT_ID,CALLER_TYP_REF_ID,IS_IN_BOUND,TRACK_NUM,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/inquiry.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('invoice');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'invoice',
'BILL_ENT_ID,INV_ID,VER,CLIENT_ID,PAY_OPTN_REF_ID,INIT_FLG,INV_NUM,DESCR,INV_AMT,MIN_DUE,DUE_DT,INV_DT,CNTC_ID,EXTND_DUE_PRD,TOP_ENT_SCHD_ID,CUR_DRCT_BAL,CUR_SSA_BAL,PRIOR_DRCT_BAL,PRIOR_SSA_BAL,ADD_ACH_AMT,ELIG_EXPR_DT,DECD_CNT,TERM_CNT,CNCL_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/invoice.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('lep_appeal');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'lep_appeal',
'PRSN_ID,LEP_APL_ID,VER,CLIENT_ID,EXT_APL_ID,APL_DT,RCV_DT,APL_DCN,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/lep_appeal.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('letter');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'letter',
'PRSN_ID,LTR_ID,VER,CLIENT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/letter.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('line_additional_diagnosis');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'line_additional_diagnosis',
'PRSN_ID,CLM_ID,SEQ_NUM,CLM_ADD_DIAG_ID,LN_ADD_DIAG_ID,VER,CLIENT_ID,DIAG_SEQ_NUM,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/line_additional_diagnosis.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('line_disallow_explanation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'line_disallow_explanation',
'PRSN_ID,CLM_ID,SEQ_NUM,LN_DISALLOW_EXPLAIN_ID,VER,CLIENT_ID,DISALLOW_AMT,EXPLAIN_CD_ID,DISALLOW_EXPLAIN_CD,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/line_disallow_explanation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('line_procedure_modifier');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'line_procedure_modifier',
'PRSN_ID,CLM_ID,SEQ_NUM,LN_PR_MOD_ID,VER,CLIENT_ID,MOD_SEQ_NUM,PR_MOD_CD,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/line_procedure_modifier.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('marx_calendar');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'marx_calendar',
'MARX_CAL_ID,VER,PAY_DT,PLAN_DTA_DUE_DT,MO_RPT_RLS_DT,CERT_OF_ENRL_DT,STRT_DT,END_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/marx_calendar.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('note');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'note',
'INQ_ID,SRC_ID,SRC_TYP_REF_ID,NTE_ORD,NTE_ID,VER,CLIENT_ID,NTE_TYP_REF_ID,WRK_BASKET,NTE,NTE_TS,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/note.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('organization_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'organization_code',
'ORG_ID,CD_VAL_ID,ORG_CD_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/organization_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('organization_contact_type');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'organization_contact_type',
'ORG_ID,CNTC_TYP_REF_ID,ORG_CNTC_TYP_ID,VER,CLIENT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/organization_contact_type.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('organizations');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'organizations',
'ORG_ID,VER,CLIENT_ID,ORG_NM,ORG_TYP_REF_ID,DESCR,EMPR_TAX_ID,WEB_SITE,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/organizations.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('payment');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'payment',
'BILL_ENT_ID,PAY_ID,VER,CLIENT_ID,PAY_AMT,CHK_NUM,PAY_SNT_DT,PAY_SRC_REF_ID,REFUN_RSN_REF_ID,ENT_BNK_ACCT_ID,CNTC_ID,CNCL_DT,SRC_TYP_REF_ID,BILL_SRC_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/payment.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_cob');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_cob',
'PRSN_ID,PRSN_COB_ID,VER,CLIENT_ID,ACT_TYP_REF_ID,BIRTH_DT,GNDR_CD,SSN,INFORMANT_RELN_REF_ID,RCPT_METHOD_REF_ID,REC_TYP,RX_ID,RX_GRP,RX_BIN,RX_PCN,RX_PLAN_PHN,COB_SRC,SEQ_NUM,MSP_RSN_CD,COVRG_CD,IND_PLCY_NUM,GRP_PLCY_NUM,EFF_DT,EXPR_DT,RELSHP_CD,PAYR_ID,PRSN_CD,PAYR_ORD,EMP_INFO_CD,LEAD_CONTRC,CLS_ACT_TYP,WCSA_AMT,WCSA_IND,WCMSA_STLMNT_DT,TOT_RX_STLMNT_AMT,IS_RX_AMT_INCL,TERM_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_cob.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_code',
'PRSN_ID,CD_VAL_ID,PRSN_CD_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_contact');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_contact',
'PRSN_ID,CNTC_ID,PRSN_CNTC_ID,VER,CLIENT_ID,CNTC_TYP_REF_ID,CNFDT_FLG,DEF_FLG,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_contact.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_event');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_event',
'PRSN_EVNT_ID,VER,CLIENT_ID,SRC_TYP_ID,PRSN_ID,ATTACH_SRC_ID,EVNT_TYP_REF_ID,CLIENT_EVNT_TYP_REF_ID,EVNT_DESCR,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_event.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_lep_event');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_lep_event',
'PRSN_ID,PRSN_LEP_EVNT_ID,VER,CLIENT_ID,LEP_AMT,TOT_UNCOVERED_MOS,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_lep_event.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_lep_profile');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_lep_profile',
'PRSN_ID,PRSN_LEP_PRFL_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_lep_profile.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_organization_relation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_organization_relation',
'PRSN_ID,ORG_ID,PRSN_ORG_RELN_ID,VER,CLIENT_ID,RELN_TYP_REF_ID,EFF_DT,EXPR_DT,SRC_SYS_REC_ID,SRC_SYS_REF_ID,VLD_FRM_DT,VLD_TO_DT,DEL',
null,
'/gemfire-logs/done/person_organization_relation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_payment_options');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_payment_options',
'PRSN_ID,PRSN_PAY_OPTN_ID,VER,CLIENT_ID,PAY_OPTN_REF_ID,WHLD_TYP_REF_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_payment_options.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_relation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_relation',
'PRSN_ID,RLTD_PRSN_ID,PRSN_RELN_ID,VER,CLIENT_ID,RELN_TYP_REF_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_relation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_role');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_role',
'PRSN_ID,PRSN_TYP_ID,VER,CLIENT_ID,PRSN_TYP_REF_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_role.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_subsidy_profile');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_subsidy_profile',
'PRSN_ID,PRSN_SBSDY_PRFL_ID,VER,CLIENT_ID,SBSDY_TYP_REF_ID,SBSDY_LEVEL_REF_ID,COPAY_CAT_REF_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_subsidy_profile.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_work_item');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_work_item',
'PRSN_ID,PRSN_WRK_ITM_ID,VER,CLIENT_ID,WRK_ITYP_REF_ID,ADD_DT,PROC_STAT_REF_ID,PROC_STAT_DT,PRSN_EVNT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_work_item.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('persons');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'persons',
'PRSN_ID,VER,CLIENT_ID,TTL,FIRST_NM,LAST_NM,MID_NM,SFX,BIRTH_DT,GNDR_REF_ID,ETHN_REF_ID,MAR_STAT_REF_ID,LANG_REF_ID,PRSN_STAT_REF_ID,EFF_DT,EXPR_DT,ATTACH_SRC_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/persons.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('phone');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'phone',
'CNTC_ID,PHN_ID,VER,CLIENT_ID,AREA_CD,LOC_EXCH,PHN_NUM,PHN_EXT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/phone.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('plan_memberships');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'plan_memberships',
'PRSN_ID,BENE_GRP_ID,PLAN_MBRSHP_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,IS_BLBL,IS_ELIG,ELIG_RSN_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/plan_memberships.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('pos_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'pos_code',
'POS_CD_ID,VER,CLIENT_ID,POS_CD,POS_DESCR,IO_IND,SERV_CAT_REF_ID,SERV_GRP_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/pos_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('postal_address');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'postal_address',
'CNTC_ID,PSTL_ADDR_ID,VER,CLIENT_ID,STR_LN1,STR_LN2,STR_LN3,CTY,CNTY,ST,PSTL_CD,CNTRY,VLDTD,VLDTN_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/postal_address.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('premium');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'premium',
'GRP_ID,PREM_CAT_ID,PREM_REC_ORD,PREM_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,PREM_AMT_RT,PREM_RATIO_FCTR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/premium.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('procedure_code');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'procedure_code',
'PR_CD_ID,VER,CLIENT_ID,PR_CD,PR_DESCR,STD_REF_CD_1,STD_REF_CD_2,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/procedure_code.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('receipt');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'receipt',
'BILL_ENT_ID,VER,CLIENT_ID,RCPT_ID,RCPT_TYP_REF_ID,RCPT_AMT,ACCT_NUM,CHK_NUM,RCPT_DT,PREM_STRT_DT,PREM_END_DT,PRD_MO_CNT,POST_DT,CONFIRM_NUM,RCPT_STAT_REF_ID,WHLD_TYP_REF_ID,DESCR,SRC_TYP_REF_ID,BILL_SRC_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/receipt.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('reference_data');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'reference_data',
'REF_DTA_ID,VER,REF_DMN,REF_CD,DESCR,VLD_FRM_DT,VLD_TO_DT,DEL',
null,
'/gemfire-logs/done/reference_data.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('returned_mail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'returned_mail',
'RTRN_MAIL_ID,VER,CLIENT_ID,PRSN_ID,RECV_DT,DOC_NUM,RTRN_MAIL_TYP_CD,RTRN_RSN,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/returned_mail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('topic');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'topic',
'INQ_ID,TPC_ID,VER,CLIENT_ID,CASE_ID,TPC_STAT_REF_ID,TPC_SUB_TYP_REF_ID,TPC_TYP_REF_ID,PRSN_ID,DESCR,DTL_DESCR,END_TM,STRT_TM,WRK_BASKET,VLD_FRM_DT,INSRT_USR,UPD_USR,INSRT_SERV_REC_TS,UPD_SERV_REC_TS,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/topic.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('unapplied_cash');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'unapplied_cash',
'UNAPP_CSH_ID,VER,CLIENT_ID,ERR_TYP_REF_ID,STAT_REF_ID,SRC_TYP_REF_ID,BILL_SRC_ID,CNCL_DT,ERR_DESCR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/unapplied_cash.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('bank_account');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'bank_account',
'BNK_ORG_ID,BNK_ID,BNK_ACCT_ID,VER,CLIENT_ID,ACCT_NM,ACCT_NUM,ACCT_TYP_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/bank_account.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('benefit_package_relation');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'benefit_package_relation',
'BENE_PKG_ID,PKG_RELN_ID,VER,CLIENT_ID,PKG_RELN_TYP_REF_ID,RLTD_BENE_PKG_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/benefit_package_relation.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_entity_contact');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_entity_contact',
'BILL_ENT_ID,CNTC_ID,BILL_ENT_CNTC_ID,VER,CLIENT_ID,CNTC_TYP_REF_ID,EFF_DT,EXPR_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,VLD_FRM_DT,VLD_TO_DT,DEL',
null,
'/gemfire-logs/done/billing_entity_contact.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_entity_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_entity_detail',
'BILL_ENT_ID,CLIENT_ID,VER,FIN_RESP_REF_ID,GRP_ID,IS_GRP_STMT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_entity_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('billing_entity_schedule');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'billing_entity_schedule',
'BILL_ENT_ID,BILL_SCHD_ID,BILL_ENT_SCHD_ID,VER,CLIENT_ID,WHLD_TYP_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/billing_entity_schedule.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('check_status');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'check_status',
'CLM_PAY_ID,CHK_ID,CHK_STAT_ID,VER,CLIENT_ID,STAT_SEQ_NUM,CHK_STAT,CHK_STAT_RSN,STAT_DT,USR_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/check_status.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_additional_diagnosis');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_additional_diagnosis',
'PRSN_ID,CLM_ID,CLM_ADD_DIAG_ID,CLIENT_ID,VER,DIAG_CD_ID,TRNSLT_DIAG_CD_ID,SBMT_DIAG_CD_ID,PRSNT_ON_ADM_IND,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_additional_diagnosis.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_detail',
'PRSN_ID,CLM_ID,SEQ_NUM,CLM_DTL_ID,VER,CLIENT_ID,LN_OF_BUS,LN_OF_BUS_IND,CAP_FND_ID,CAP_POOL_ID,POS_CD_ID,PR_CD_ID,DIAG_CD_ID,RLTD_DIAG_CD_ID,CUR_CLM_STAT_CD,SERV_FRM_DT,SERV_TO_DT,RM_TYP_ID,CLM_CHRG_AMT,ANES_MOD,CLM_RT_AMT,ALWD_AMT,CONSIDERED_AMT,NUM_OF_UNT,ALWD_NUM_OF_UNT,DEDUCTABLE_AMT,COPAY_AMT,COINSURANCE_AMT,RISK_WHLD_AMT,CLM_PD_AMT,DISALLOW_AMT,EXPLAIN_CD_ID,DISALLOW_EXPLAIN_CD,AGREE_PRC,DISC_AMT,SUPPL_DISC_AMT,ITS_DISC_AMT,PRVD_NTWK_STAT,REF_IND,PRE_AUTH_IND,CAPITATED_SVIND,SUBS_PAY,PRVD_PAY,PRE_PD_AMT,SERV_RPT_CAT,EXPER_CAT,ACCT_CAT,REF_ID,REF_SEQ_NUM,PRE_AUTH_ID,PRE_AUTH_SEQ_NUM,PRE_AUTH_SRC,IO_IND,AMBUL_PAY_CD,AMBUL_PAY_STAT,CLM_837_SEQ_NUM,MED_UTIL_EDIT_IND,SBMT_DIAG_CD,SBMT_RLTD_DIAG_CD,TRNSLT_DIAG_CD,TRNSLT_RLTD_DIAG_CD,PRVD_SPECIALTY,PRVD_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_payment');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_payment',
'CLM_PAY_ID,VER,CLIENT_ID,CLM_PAY_DT,CLM_PAY_REF,CLM_PAY_TYP,CLM_PAY_SUB_TYP,LN_OF_BUS,PAYEE_TYP,SUBS_ID,PRVD_ID,CMB_CLM_FLG,PRD_END_DT,ORIG_AMT,DEDUCTABLE_AMT,CLM_PAY_NET_AMT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_payment.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_payment_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_payment_detail',
'PRSN_ID,CLM_ID,CLM_PAY_ID,CLM_PAY_DTL_ID,VER,CLIENT_ID,LN_OF_BUS,ORIG_AMT,EOB_FLG,VIO_FLG,NTWK_FLG,PROMPT_PAY_DISC,DISC_PCT,PRIOR_PD_AMT,CLM_PAY_NET_AMT,PROMPT_PAY_CD,OVRD_FLG,INT_AMT,CALC_INT,REIMB_AMT,PRIOR_REIMB,CONFIDENTIAL_FLG,ALLOWABLE_AMT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_payment_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_payment_reduction');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_payment_reduction',
'CLM_PAY_RDCTN_ID,VER,CLIENT_ID,PAY_RDCTN_REF,PAY_RDCTN_SUB_TYP,PLAN_YR,TAX_YR,PAY_RDCTN_TYP,CRT_DT,PAYEE_TYP,PRVD_ID,SUBS_ID,AUTO_PAY_RDCTN_FLG,RDCTN_ORIG_AMT,RECOVERED_AMT,RECV_AMT,WO_AMT,RDCTN_NET_AMT,RDCTN_STAT,DISALLOW_EXPLAIN_CD,USR_ID,PREM_TYP_FLG,EXT_PAY_FLG,RDCTN_DESCR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_payment_reduction.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_reduction_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_reduction_detail',
'PRSN_ID,CLM_ID,CLM_PAY_RDCTN_ID,CLM_RDCTN_DTL_ID,VER,CLIENT_ID,PAYEE_TYP,PRVD_ID,SUBS_ID,CRT_DT,ORIG_AMT,AUTO_PAY_RDCTN_FLG,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_reduction_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_reduction_history');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_reduction_history',
'CLM_PAY_RDCTN_ID,CLM_RDCTN_HIST_ID,VER,CLIENT_ID,SEQ_NUM,RDCTN_EVNT_TYP,CLM_PAY_ID,REC_DT,PRD_END_DT,RDCTN_AMT,USR_ID,RDCTN_RSN,CHK_NUM,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_reduction_history.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('claim_status');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'claim_status',
'PRSN_ID,CLM_ID,SEQ_NUM,CLM_STAT_ID,VER,CLIENT_ID,CLM_STAT_CD,CUR_ITS_STAT_CD,CLM_STAT_TS,STAT_RSN_REF_ID,USR_ID,ROUTED_USR_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/claim_status.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('complaint_status');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'complaint_status',
'INQ_ID,COMPLAINT_ID,COMPLAINT_STAT_ID,VER,CLIENT_ID,REJ_RSN_REF_ID,COMPLAINT_STAT_REF_ID,COMPLAINT_STAT_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/complaint_status.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('contact_type_contact');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'contact_type_contact',
'CNTC_ID,ORG_CNTC_TYP_ID,CNTC_TYP_CNTC_ID,VER,CLIENT_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/contact_type_contact.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('exhibit_group');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'exhibit_group',
'EXHIBIT_GRP_ID,VER,CLIENT_ID,BENE_GRP_ID,TRIGGERING_EXHIBIT_ID,LANG_REF_ID,SUPPRESSED_FLG,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/exhibit_group.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('exhibit_group_exhibit');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'exhibit_group_exhibit',
'EXHIBIT_ID,EXHIBIT_GRP_ID,EXHIBIT_GRP_EXHIBIT_ID,VER,CLIENT_ID,CMPNT_NUM,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/exhibit_group_exhibit.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('general_ledger_map');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'general_ledger_map',
'GL_MAP_ID,VER,CR_ACCT_REF_ID,DR_ACCT_REF_ID,GL_MAP_TYP_REF_ID,GL_MAP_NM,DESCR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/general_ledger_map.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('invoice_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'invoice_detail',
'BILL_ENT_ID,INV_ID,INV_DTL_ID,VER,CLIENT_ID,ENT_SCHD_STRT_DT,ENT_SCHD_END_DT,BNFC_ID,WHLD_TYP_REF_ID,DTL_TYP_REF_ID,BNFC_RELN_REF_ID,INV_DTL_AMT,CUR_FLG,CR_FLG,BENE_GRP_ID,SRC_TYP_REF_ID,BILL_SRC_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/invoice_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('invoice_status');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'invoice_status',
'BILL_ENT_ID,INV_ID,INV_STAT_ID,VER,CLIENT_ID,INV_STAT_DT,INV_STAT_REF_ID,DESCR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/invoice_status.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('lep_appeal_decision');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'lep_appeal_decision',
'PRSN_ID,LEP_APL_ID,LEP_APL_DEC,VER,CLIENT_ID,APL_DEC_DT,LEP_APL_DEC_REF_ID,RCV_DT,MAIL_NOTICE_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/lep_appeal_decision.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('letter_detail');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'letter_detail',
'PRSN_ID,LTR_ID,LTR_DTL_ID,VER,CLIENT_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/letter_detail.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('letter_job');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'letter_job',
'PRSN_ID,LTR_DTL_ID,LTR_JOB_ID,VER,CLIENT_ID,SRC_REF_ID,LTR_SRC_NUM,QA_DT,INBOUND_SRC_REF_ID,LTR_INBOUND_SRC_NUM,PG_CNT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/letter_job.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('letter_register');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'letter_register',
'PRSN_ID,LTR_ID,LTR_RGSTR_ID,VER,CLIENT_ID,EXHIBIT_ID,RQST_DT,TGR_DT,PRT_DT,MAIL_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/letter_register.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('letter_work_item');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'letter_work_item',
'PRSN_ID,LTR_RGSTR_ID,PRSN_WRK_ITM_ID,LTR_WRK_ITM_ID,VER,CLIENT_ID,WRK_ITM_EXIBIT_EFF_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/letter_work_item.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_event_attribute');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_event_attribute',
'PRSN_EVNT_ID,PRSN_EVNT_ATTR_ID,VER,CLIENT_ID,ATTR_TYP_REF_ID,SEQ_EVNT_NUM,NMRC_EVNT_ATTR,TXT_EVNT_ATTR,TS_EVNT_ATTR,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_event_attribute.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_event_status');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_event_status',
'PRSN_EVNT_ID,PRSN_EVNT_STAT_ID,VER,CLIENT_ID,STAT_REF_ID,EVNT_STAT_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_event_status.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_event_status_reason');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_event_status_reason',
'PRSN_EVNT_STAT_ID,PRSN_EVNT_STAT_RSN_ID,VER,CLIENT_ID,RSN_REF_ID,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_event_status_reason.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('person_lep_profile_record');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'person_lep_profile_record',
'PRSN_ID,PRSN_LEP_PRFL_ID,PRSN_LEP_PRFL_REC_ID,VER,CLIENT_ID,LEP_REC_TYP_REF_ID,CREDITABLE_COVRG_FLG,INCR_UNCOVERED_MOS,PRIOR_PLAN_UNCOVERED_MOS,ATTEST_RSPNS_TYP_REF_ID,ELIG_STRT_DT,END_OF_IEP,GAP_STRT_DT,GAP_END_DT,BEQ_RSPNS_DT,RSPNS_TO_ATTEST_DT,LEP_CMS_CONFIRM_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/person_lep_profile_record.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('premium_category');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'premium_category',
'GRP_ID,PREM_CAT_ID,VER,CLIENT_ID,PREM_TBL_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/premium_category.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('premium_part');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'premium_part',
'GRP_ID,PREM_PART_ID,VER,CLIENT_ID,PREM_ID,SBSDY_LEVEL_REF_ID,RESP_PRTY_REF_ID,SPLT_METHOD_REF_ID,PREM_PART_AMT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/premium_part.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('premium_table');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'premium_table',
'GRP_ID,BENE_GRP_ID,PREM_TBL_ID,VER,CLIENT_ID,PREM_TYP_REF_ID,EFF_DT,EXPR_DT,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/premium_table.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
SYS.CREATE_ALL_BUCKETS('topic_communication');
CALL SYSCS_UTIL.IMPORT_DATA_EX(
'ods',
'topic_communication',
'CMCN_INQ_ID,TPC_INQUIRE_ID,CMCN_ID,TPC_ID,VER,CLIENT_ID,INSRT_USR,UPD_USR,INSRT_SERV_REC_TS,UPD_SERV_REC_TS,VLD_FRM_DT,VLD_TO_DT,SRC_SYS_REF_ID,SRC_SYS_REC_ID,DEL',
null,
'/gemfire-logs/done/topic_communication.sql',
',',
null,
null,
0,
0,
2,
0,
null,
null
);
